### ISSUE TITLE
Wood crosses take up two different tiles as opposed to one.

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#1019]
Issue reported from  Round ID: 1008 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

The large, wooden crucifixes take up two tiles of room (the bottom and the top one) as opposed to a single tile at the bottom and the ability to walk under the one that's supposed to be going up into the air.

**Comment by BobJoga** [comment]
alright bro  this SHOULD be easy to fix

**Comment by BobJoga** [comment]
hold on bro i got you

**Comment by BobJoga** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/1030

**Comment by BobJoga** [comment]
pr merged you can close this now baby

**Comment by DeusSepulchre** [comment]
Great
