### ISSUE TITLE
Virology: Necrotizing Fasciitis Thresholds swapped with another disease

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#1024]
Issue reported from  Round ID: 1008 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

The symptoms listed for Necrotizing Fasciitis are as follows:
_______________________________________________________________________________________________________
Doubles the intensity of the immolation effect, but reduces the frequency of all of this symptom's effects.
--
Increases explosion radius and explosion damage to the host when the host is wet.
--
Additionally synthesizes chlorine trifluoride and napalm inside the host. More chemicals are synthesized if the resistance 9 threshold has been met.
_______________________________________________________________________________________________________

The listed symptoms for Necrotizing Fasciitis seem to be the symptoms from another disease called Alkali Perspiration from another code base. They do not match any standard Necrotizing Fasciitis symptoms. They match Alkali Perspiration. This could mean a couple things because I haven't read the code yet for Necrotizing Fasciitis on this server
A: The disease itself works properly and has correct thresholds assigned to it but the written symptoms listed in the machine were copy and pasted wrong from another virus.
B. And this would be more hellish for the coders. Possibly necrotizing fasciitis is a splice of itself and Alkali Perspiration or just the wrong disease.

**Comment by BobJoga** [comment]
Seems this is an upstream problem. I could modularly fix it but i recommend reporting the issue upstream.

**Comment by DeusSepulchre** [comment]
If that's the case I'll close the issue for now. Great.
