### ISSUE TITLE
Grilled foods not updating their sprite.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1046]
## Reproduction:

![image](https://user-images.githubusercontent.com/7543955/78090710-e0aed980-7398-11ea-890b-479dc8af740a.png)

Just Grill it.

Also, the grill tends to emit puffs of smoke even when not being used.

**Comment by CinderWC** [comment]
After testing it myself on the current build, this issue appears fixed.

![lxTF8Qo](https://user-images.githubusercontent.com/51722986/79544472-5e5c3000-808f-11ea-9e08-44f425b6ede3.png)
