### ISSUE TITLE
Blueshield cargo access 

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat13#1125]
## Reproduction:

during this shift I had to access cargo, however I have no access to cargo offices, however while in cargo offices I am able to open the cargo bay doors meaning I have cargo bay access but not offices.

**Comment by CinderWC** [comment]
@Strazyplus Hello! What map was this on?

**Comment by Strazyplus** [comment]
@CinderWC Sorry did not notice the reply, Box station but I believe it is so on all.

**Comment by CinderWC** [comment]
@Strazyplus I tested the access and i have found the issue in question. The Office door has the wrong var set for it's Access and requires Mail Room Access rather than Cargo Access. Fixing it now by making it Cargo access

**Comment by CinderWC** [comment]
Issue fixed and PRed in  #1185
