### ISSUE TITLE
Delta station: floating Prisoner Telescreen in space + improperly wired Detective Office

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#1130]
Issue reported from  Round ID: 1065 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

On Delta station there's a floating prisoner Telescreen in space between the perma brig and the HoS office. Furthermore, it seems there are wiring issues with the Detective's new office position that is probably related to the new Blueshift office next to it. From what I can understand the APC isn't wired and we had a power failure towards the start of the shift. This is similar to other issues the station has had during brig related changes such as when the Warden's Office was missing a wire. The Warden's Office issue has since been fixed.

**Comment by CinderWC** [comment]
This issue has been partially adressed in another PR which fixed the telescreen in space.
I have however now adressed the Detective's power issues that were still there in #1185
