### ISSUE TITLE
Deconstructing YouTool gives Booze-O-Mat Restock

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1157]
## Reproduction:

Deconstruct a YouTool Vendor (and possibly others?) Get the wrong restocking unit back.

**Comment by Trilbyspaceclone** [comment]
Maybe they are slavic tools?

**Comment by CinderWC** [comment]
This issue is currently PRed to be fixed on upstream: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11886

**Comment by CinderWC** [comment]
This was fixed in https://github.com/Skyrat-SS13/Skyrat13/pull/1265
