### ISSUE TITLE
There are 2 security records consoles in the engineering post on delta.

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#1167]
Title. It should be a security records console and a security CAMERA console, not 2 security records consoles. https://i.imgur.com/dAxYjKR.png

**Comment by Strazyplus** [comment]
I reeeee'd so hard.

**Comment by CinderWC** [comment]
@CoreFlare The screenshot and issue are on Pubby, not Delta. Please report the bug properly next time and save me some of my own time.

**Comment by CinderWC** [comment]
This issue has been adressed in #1185
