### ISSUE TITLE
Mesmerize Permanently Cripples

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1179]
## Round ID:

1095

## Reproduction:

Get Mesmerized, get pulled away from it, combat mode button flashes forever, permanently crippled, even after the mesmerize icon is gone.

**Comment by Arturlang** [comment]
Its fixed upstream

**Comment by Arturlang** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/609

**Comment by CinderWC** [comment]
This has been fixed. Please close this.

@Owai-Seek
@Azarak
@Useroth
