### ISSUE TITLE
Old Station cant spawn on generation and cant be placed by admins

### ISSUE THREAD

**Issue by AsaiasWolffe** [Skyrat-SS13/Skyrat13#1184]
I dont have much in the way of details but what I do know is old station wont roll on restart and admins (specifically planetary) cant manually spawn it in. It gives some sort of error when ever an admin attempts to spawn it (i know its not very helpful but it was a while ago and im not an admin to get the error for myself)
The old station rework was done on my request and was finished a while ago and i have yet to be able to set foot on it and that fact kills me.

**Comment by CinderWC** [comment]
After a long time of having this issue up we have  finally found the cause for this issue and fixed it.

Thank you for reporting!
