### ISSUE TITLE
New Piano_Synth interface bug

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat13#1186]
Issue reported from  Round ID: 1103 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

Piano_Synth, if the Volume Dropoff Threshold is raised, it cannot be set below 30 thereafter.

**Comment by CinderWC** [comment]
I was unable to recreate this issue, both in a private server AND on the actual Skyrat server itself.
I was able to modify the Volume Dropoff Threshold higher than 30 (To around 50 and 60) and then drop it down low all the way to 10.

I will consider this issue fixed
