### ISSUE TITLE
[BOX] There is 1 security records console in the new medical post.

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#1187]
There should be a sec records and a cam console. There is only records. Whoever made these new sec posts is bad.

**Comment by CinderWC** [comment]
@CoreFlare 
![before](https://user-images.githubusercontent.com/51722986/79061315-57987c00-7c8f-11ea-8eb5-d6bca2a56930.png)
![after](https://user-images.githubusercontent.com/51722986/79061317-59623f80-7c8f-11ea-9c34-ca171df7e564.png)

ok very cool

**Comment by CinderWC** [comment]
This issue has been adressed in #1185
