### ISSUE TITLE
Different skin helmets, helmet light no sprite.

### ISSUE THREAD

**Issue by MrBobCool** [Skyrat-SS13/Skyrat13#1195]
Issue reported from  Round ID: 1124 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

>Altclick helmet.
>Pick different skin.
>Attach flashlight.
>Turn flashlight on.
>Permanently make helmet invisible.

**Comment by CinderWC** [comment]
This issue has been bandaid fixed in #1248

Please close @Azarak or @Useroth
