### ISSUE TITLE
Some preferences don't save(in pref tab)

### ISSUE THREAD

**Issue by Commandersand** [Skyrat-SS13/Skyrat13#1203]
## Round ID:
1132

## Reproduction:
for sure it happens with sounds prefs, like admin midis and lobby music

**Comment by CinderWC** [comment]
I personally have never had this issue. Does this still happen?

**Comment by Azarak** [comment]
Should be fixed, is this still an issue? @Commandersand

**Comment by CinderWC** [comment]
As there has been no response from OP about the state of this issue and i personally have not encountered it, as well as not hearing any more complaints about preferences not saving. I will now be closing this issue.

If this issue still persists, please feel free to reopen the ticket or create a new one
