### ISSUE TITLE
Space Cash can no longer purchase premium items.

### ISSUE THREAD

**Issue by BurgerLUA** [Skyrat-SS13/Skyrat13#1204]
Round ID: 1132.

Likely from the new update. Don't know if feature or bug.

**Comment by CinderWC** [comment]
@BurgerLUA Are we talking about the wads of cash or Coins. Because i dont think it is actually intended for Space Cash to work

**Comment by BurgerLUA** [comment]
Wads of cash. I remember it being able to take wads of cash.

**Comment by CinderWC** [comment]
I have tested this on my upstream repository. The same thing happens there, which leads me to believe that this was intentional.

Closing this for now as it does not appear to be an issue, but rather intended
