### ISSUE TITLE
Newly-created photos don't load in, crash upon examining.

### ISSUE THREAD

**Issue by EikoBiko** [Skyrat-SS13/Skyrat13#1208]
If you take a picture, or create one with the scanner (scanning your butt for example), the photo will be invisible until you restart your client. If you examine the invisible photo before restarting the client, the game crashes.

**Comment by CinderWC** [comment]
I was unable to recreate this issue, both in a private server AND on the actual Skyrat server itself.

Could i perhaps have more info on this?

**Comment by CinderWC** [comment]
I was unable to recreate this issue, both in a private server AND on the actual Skyrat server itself.
I will consider this solved and close the issue for the time being.

If this happens again, please reopen this issue or make a new one and make sure to tell me that i am stupid. (You may screenshot this and just...insert that)
