### ISSUE TITLE
Acid -really- hates light fixtures. (Permanent Acid Decal)

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1214]
## Round ID:
1138

## Reproduction:
Acid Scrubbers touch lights.
![image](https://user-images.githubusercontent.com/7543955/79376843-c2b0af80-7f28-11ea-96ad-5153c7aba9ce.png)

**Comment by CinderWC** [comment]
This has been fixed upstream.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11876
