### ISSUE TITLE
Energy Revolver sprite shows in wrong directional hand.

### ISSUE THREAD

**Issue by MrBobCool** [Skyrat-SS13/Skyrat13#1216]
Issue reported from  Round ID: 1139 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

Holding the energy revolver in your left hand shows it in your right, holding it in your right shows it in your left, sprite wise of course.

**Comment by CinderWC** [comment]
Fixing once I wake up later
