### ISSUE TITLE
Forensic Scanner doesn't work on blood

### ISSUE THREAD

**Issue by Sir-Lagsalot** [Skyrat-SS13/Skyrat13#1218]
## Reproduction:
You can't use the forensic scanner to scan blood on the floor to get forensic information on it, like the blood type or DNA sequence.
![image](https://user-images.githubusercontent.com/52263717/79399826-5e0a4a80-7f52-11ea-8d6a-5c8a94de3dae.png)

**Comment by EikoBiko** [comment]
>no blood on the blood
Good stuff!

**Comment by CinderWC** [comment]
This issue seems to have originated from upstream as they also have an old, still open, Issue report about it.
https://github.com/Citadel-Station-13/Citadel-Station-13/issues/11405

**Comment by CinderWC** [comment]
I got Ghommie to PR a fix for this upstream. And considering that that will 100% get merged i will be closing this issue now.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11906
