### ISSUE TITLE
Power Armour sprite bug 

### ISSUE THREAD

**Issue by BelusOfBablyon** [Skyrat-SS13/Skyrat13#1354]
## Round ID: 1168

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tgstation hosted servers: Yes, Skyrats
[Round ID]: 1168

## Testmerges:

I'm unsure, I looked for a PR with it earlier but couldn't find one

## Reproduction:
When I put on power armour, the sprite massively bugged. It made all my clothes invisible except for underwear and got rid of the frills on my head as long as making my snout flat like a humanoid head. 
![power](https://user-images.githubusercontent.com/63973960/79696424-94a6d480-8274-11ea-9b3e-6c01fef4acd0.png)

**Comment by CinderWC** [comment]
yeah that sure helps...

**Comment by BobJogaIsForkinBanned** [comment]
nice

**Comment by CinderWC** [comment]
An updated and more elaborated version was made of this issue. Closing
https://github.com/Skyrat-SS13/Skyrat13/issues/1452
