### ISSUE TITLE
crafting menu NTOS error

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat13#1415]
Round ID: 1177

Date and Time of Issue: 3:30-EST 4/20/20

Tried to open the crafting menu

What Map did this Issue occur on: Meta-station, probably all (?)

Testmerges (If Applicable): N/A

 Reproduction: open the crafting menu
get slapped with 
**Error: JSON parsing error: Syntax error
   at Anonymous function (http://127.0.0.1:50173/tmp13960/tgui.bundle.js:1:90104)
   at window.initialize (http://127.0.0.1:50173/tmp13960/tgui.bundle.js:1:89866)
   at eval code (eval code:1:1)**

Possible Screenshots of the Issue in question: 
![image](https://user-images.githubusercontent.com/62520989/79794368-215a9c80-8320-11ea-9c7c-c1ab22ca6086.png)

**Comment by RatFromTheJungle** [comment]
update, all NTOS is broke

**Comment by BobJogaIsForkinBanned** [comment]
Apparently an upstream issue.
https://github.com/Skyrat-SS13/Skyrat13/pull/1407

**Comment by PersianXerxes** [comment]
Fixed by #1429, btw @RatFromTheJungle
