### ISSUE TITLE
Brig Doctor Hat Broken

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#1419]
Issue reported from  Round ID: 1177 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

When I joined as a Brig Doctor the hat on my head both appeared on my in-game model and as an icon on my head slot. However, after removing it from my head it immediately went invisible in my hand and remained invisible on my head as well when put back on. Alt clicking it to flip the hat did not fix the issue. This is probably part of a greater issue regarding glitched clothing. Beware of modular code.

**Comment by CinderWC** [comment]
I have been unable to replicate this issue on my private repository

**Comment by CinderWC** [comment]
This issue was also not able to be replicated on the live server, leading me to believe this is an isolated instance OR fixed

**Comment by CinderWC** [comment]
Reopening after similar issues are appearing

**Comment by CinderWC** [comment]
Reopening after issues similarly to this one appeared
