### ISSUE TITLE
Finicky Chem Master

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#1420]
Issue reported from  Round ID: 1177 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

After filling a beaker with 60 units of bicaridine I put it into the chem master only to be unable to transfer the chemicals to the buffer. I walked away, did other things in the round, then it worked for me. Later, the HoP came by asking about it being broken and another player ICly said he was having the same issue. Although the HoP was able to successfully buffer and print a chlorine pill I tried a new beaker and was again unable to move things to the buffer. I will comment on this issue if I figure out anything else during this round that might clarify the problem.

**Comment by CinderWC** [comment]
Hello, we will look into this.

**However please make sure to use the proper template next time**

**Comment by CinderWC** [comment]
Tested locally, works fine. Testing it on the server now.

**Comment by CinderWC** [comment]
Any updates after your testing of this @jjpark-kb ?

**Comment by CinderWC** [comment]
This was caused by a current testmerge which has since been updated. It is fixed
