### ISSUE TITLE
Blueshield uniform and vest invisible

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat13#1428]
## Reproduction:The vest object icon are invisible but visible worn on mob. 

![image](https://user-images.githubusercontent.com/6706750/79807854-21679600-833a-11ea-957d-56fe179816b5.png) // invisible on hud

![image](https://user-images.githubusercontent.com/6706750/79807889-347a6600-833a-11ea-8a16-7e83e7e08400.png) // uniform looks correct

![image](https://user-images.githubusercontent.com/6706750/79808230-2ed15000-833b-11ea-9982-bb0ad01e71df.png) // invisible on ground

**Comment by BobJogaIsForkinBanned** [comment]
Noted. Will be fixing it.

**Comment by BobJogaIsForkinBanned** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/1437
Can close it now.
