### ISSUE TITLE
Synthetic Lizardperson cannot get nanites

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat13#1468]
## Reproduction: 

Synthetic lizardperson characters are unable to receive nanites I have noticed this bug for some time,

**Comment by Azarak** [comment]
This is intended behaviour. IPC's and synthlizards are classed as ROBOTIC thus making nanites and the usual viruses not work on them

**Comment by CinderWC** [comment]
![MmxYeVf](https://user-images.githubusercontent.com/51722986/80005568-0cb70980-84c4-11ea-8442-cd54ad57cd5b.png)

**Comment by Strazyplus** [comment]
w e h
