### ISSUE TITLE
Cashbot examine with massive amount of newlines

### ISSUE THREAD

**Issue by Akrilla** [Skyrat-SS13/Skyrat13#1473]
## Reproduction:

Examine Cashbot. Possibly when it doesn't have maint access specifically. 

## Possible Screenshots of the Issue in question:

![image](https://user-images.githubusercontent.com/18756865/80018228-9fa87180-84cd-11ea-9ae3-a097401f3c38.png)

**Comment by RatFromTheJungle** [comment]
all electronics do this

**Comment by Akrilla** [comment]
I've never seen this ever

**Comment by CinderWC** [comment]
Me neither.

**Comment by CinderWC** [comment]
I have looked into the matter extensively and i have been unable to replicate this issue in any way whatsoever. This is likely caused by the coding done by the person that has made the bot.

It may be intentional by the creator of the Cashbot
