### ISSUE TITLE
While in critical in VR, you cannot exit VR

### ISSUE THREAD

**Issue by Jamini** [Skyrat-SS13/Skyrat13#1474]
## Details

If your VR avatar enters critical, but does not die, you are unable to exit VR until it dies.

## Possible Screenshots of the Issue in question:

![image](https://user-images.githubusercontent.com/1775680/80025490-c0150380-84ae-11ea-8320-e2d9c0847db8.png)

**Comment by CinderWC** [comment]
This is intended. VR is supposed to simulate what it is like to be in that situation. With simulated pain and Unconsciousness.

You cant leave VR while unconscious as all of your senses are gone
