### ISSUE TITLE
Walls for xenobio in the syndicate base aren't actually plastitanium walls.

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#1484]
https://i.imgur.com/GfJHkYv.png

See the split? These aren't plastitanium walls. They are most likely indestructible walls that LOOK like plastitanium, because somebody got lazy while mapping and forgot to double check what they were placing.

**Comment by CinderWC** [comment]
bruh moment

**Comment by CinderWC** [comment]
Apparently Forrest says this is intended but i am still changing this shit.

However. This is NOT an issue as it is indeed intended
