### ISSUE TITLE
Impossible to fix burn in your prosthetics

### ISSUE THREAD

**Issue by Sir-Lagsalot** [Skyrat-SS13/Skyrat13#1505]
For a while now, if you have a prosthetic limb with burn damage and go to use wires on it, you'll get the "you start fixing some of the wires" message, but no progress bar will come up and it won't actually fix anything. Fixing brute with a welder still works fine.

**Comment by CinderWC** [comment]
Upstream issue: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12007

**Comment by Commandersand** [comment]
if you have someone else do it it works
while it gets fixed

**Comment by CinderWC** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/1534
