### ISSUE TITLE
Black Tango Dress doesn't display with digigrade legs.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1516]
## Date and Time of Issue:
3-24-20 8PM EST

## What Map did this Issue occur on:
Box

## Reproduction:
Put it on.

**Comment by CinderWC** [comment]
I dont even test on my Skyrat Repo anymore... Jumped straight to my Cit Repo to find out its on their side

**Comment by CinderWC** [comment]
Fixed upstream. Will leak down to us
