### ISSUE TITLE
Layering issues with furniture when carrying people

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1528]
## Round ID:
1209

## Date and Time of Issue:
~5AM EST 4-25-20

## What Map did this Issue occur on:
Pubby

## Reproduction:
Buckle into furniture while holding someone.

## Possible Screenshots of the Issue in question:
![image](https://user-images.githubusercontent.com/7543955/80275621-8ad80380-86b0-11ea-849b-991ca85ebac7.png)

![image](https://user-images.githubusercontent.com/7543955/80275668-d094cc00-86b0-11ea-93e1-c35c63db440e.png)

**Comment by CinderWC** [comment]
If this happens down here it definitely happens upstream

**Comment by CinderWC** [comment]
Tested. Upstream issue.

**Comment by CinderWC** [comment]
Well my OCD wants me to close this so i will now.

Upstream has a PR to fix this but it has been open and ignored for a while so i guess fixing bugs is the least of their priorities

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12023
