### ISSUE TITLE
Maid Apron doesn't display on Maid Outfit

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#1536]
## Round ID:
1210

## Date and Time of Issue:
11 AM EST 4/25/20

## Reproduction:

Place the outfit on, apron or no apron, it does not display.

Just put the outfit on.

## Possible Screenshots of the Issue in question:
![dreamseeker_qt8AOVOsWp](https://user-images.githubusercontent.com/7543955/80289977-4ed48b00-8710-11ea-8b61-1079a8ce7642.png)
![dreamseeker_lsNpLFMe0m](https://user-images.githubusercontent.com/7543955/80289979-51cf7b80-8710-11ea-80fc-f6da1654f30f.png)

**Comment by CinderWC** [comment]
Tested. Upstream issue.

**Comment by jjpark-kb** [comment]
this is fixed

**Comment by jjpark-kb** [comment]
![image](https://user-images.githubusercontent.com/55967837/88358255-30485500-cd3c-11ea-876f-8cb765abe2dc.png)
![image](https://user-images.githubusercontent.com/55967837/88358257-350d0900-cd3c-11ea-904a-7d58f0ff39b4.png)
