### ISSUE TITLE
Explorer suit not using naga taur sprite

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat13#1566]
## Reproduction:

**Explorer suit not using naga sprites**
>wear explorer suit on naga, it will give you legs.

Explorer suit has naga taur sprites but does not use them, attempted to resolve but could not find the cause.

**Comment by CinderWC** [comment]
As not even Bob knows how to fix it, i will give out a grand reward of 5 Dogecoins to the person to fix this issue.

**Comment by Strazyplus** [comment]
Make it ten.

**Comment by Strazyplus** [comment]
Found, fixed and tested nondigi, digi, and taur and made a PR in 30 minutes.
