### ISSUE TITLE
Head of security hardsuit helmet sprite is broken.

### ISSUE THREAD

**Issue by kperdue2002** [Skyrat-SS13/Skyrat13#1588]
Issue reported from  Round ID: 1227 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

As said in the title. The helmet deploys, but the helmet hides all head gear including hair and facial hair, and does not show up, leaving you looking bald.

**Comment by CinderWC** [comment]
Fixed in newest commit in https://github.com/Skyrat-SS13/Skyrat13/pull/1577
