### ISSUE TITLE
Power Armor explodes when you try to construct it

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat13#1595]
## Round ID:
1230

## Date and Time of Issue:
4/28/20, 11:43AM

## What Map did this Issue occur on:
PubbyStation

## Testmerges (If Applicable):
#1577 #1496 #1405 #1499 #1504

## Reproduction:
Get all of the Power Armor parts together
Put them on the chassis
Wrench it
Weld it
Eat shit and die because the welding part of the construction makes it fucking explode

**Comment by CinderWC** [comment]
What in the fuck

**Comment by IronEleven** [comment]
Fixed in PR #1599
