### ISSUE TITLE
Glasswork containers have broken volume.

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat13#1625]
![dreamseeker_d28NmfJw6t](https://user-images.githubusercontent.com/49801705/80678532-aeb89200-8a80-11ea-956e-851b2f168db1.png)

Issue reported from  Round ID: 1242 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

/obj/item/reagent_containers/glass/beaker/flask/large
Large Flask desc displays a capacity of 80u, transfer can only be set to 60u max, and the container volume = 1u. Oddly, could not varedit this fixed, it would persistently take only 1u before declaring it was full.

/obj/item/reagent_containers/glass/beaker/flask/spouty
Similar to large flask, displays a 120u capacity, volume =1, transfers 1u before being full.

Additionally; recommendation to make glassblowing rod (/obj/item/glasswork/blowing_rod) craftable from metal rod, and tools (/obj/item/glasswork/glasskit) from wood+metal, to facilitate ashwalker trading and tool availability.

**Comment by C-Kuha** [comment]
Finally, a good issue report.

**Comment by Afya212** [comment]
Imma take a peak.

**Comment by Afya212** [comment]
Wasn't able to replicate the issue, not sure if it was already fixed in a PR or that.
