### ISSUE TITLE
Primary color don't show up on-mob for Polychromic Cloak

### ISSUE THREAD

**Issue by NopemanMcHalt** [Skyrat-SS13/Skyrat13#1630]
## Round ID:

1246
## Date and Time of Issue:
08:16, 30.04.2020 (4/30/2020)

## What Map did this Issue occur on:
Delta Station

## Testmerges (If Applicable):
N/A

## Reproduction:
1. Get polychromic cloak (from loadout or random spawn, or if someone dropped it)
2. Try to set color for Primary.
3. It will update inventory icon, but not on-mob icon.

## Possible Screenshots of the Issue in question:
![image](https://user-images.githubusercontent.com/36963049/80715172-a868fb00-8afe-11ea-9837-2b56806c3a01.png)

**Comment by C-Kuha** [comment]
Yeah. A massive pain in terms of style.  I hope this issue gets more attention.

**Comment by jjpark-kb** [comment]
fixed

**Comment by NopemanMcHalt** [comment]
> fixed

Appreciated, but for future reference: put "Fixes #`ISSUEID`"  to automatically close it when merged.

**Comment by jjpark-kb** [comment]
> > fixed
> 
> Appreciated, but for future reference: put "Fixes #`ISSUEID`" to automatically close it when merged.

See: 
![image](https://user-images.githubusercontent.com/55967837/82134923-226dd500-97cb-11ea-89d0-d7e6505c61cb.png)
I originally did this, but I was told to fix it upstream. Upstream didnt put a fix # for us so, I manually closed it.
