### ISSUE TITLE
Syndicate Lavaland Base Gas Tanks

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat13#1698]
## Reproduction: The glass holding the Plasma inside the tank on Lavaland Syndicate Base bursts open from pressure, likely due to it not being made of Plasmaglass, I am unsure if the gas miner shuts off or anything like that as I didn't check, but they run exactly like the gas miners in atmospherics.
In edition, the computer consoles in front of the tanks do not work, when checked, they come up as a blank white window, and the window cannot be taken out unless you restart the client

**Comment by jjpark-kb** [comment]
changing windows to r. plasma glass. 
Keeping issue open for the second issue.
