### ISSUE TITLE
Night-Lighting only updates when security level is increased or decreased

### ISSUE THREAD

**Issue by NopemanMcHalt** [Skyrat-SS13/Skyrat13#1710]
## Round ID:
1274

## Date and Time of Issue:
04.05.2020 (5/4/2020) 12:49

## What Map did this Issue occur on:
MetaStation, however happens on all maps.

## Testmerges (If Applicable):
N/A

## Reproduction:
1. Let the time flow.
2. Find out that night-lighting doesn't happens.
3. Increase or decrease security level.
4. Suddenly it decides to enable or disable night-lighting.

## Possible Screenshots of the Issue in question:
N/A

**Comment by jjpark-kb** [comment]
Not a bug, but intended. Perhaps I can switch it on later.
