### ISSUE TITLE
Legion cores are broken

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#1736]
When you use a legion core by pressing Z it doesn't give you the speed buff. In fact, it might work just like the old legion cores, I'm not sure though. The main issue is that if you use a legion core by pressing Z instead of clicking yourself, you are now permanently locked into the speed that you had before you used the legion core, until you use another legion core properly.

Get damaged to about softcrit, use a legion core by holding it in your hand and pressing Z, and presto, you are now speedlocked to softcrit speeds until you get another legion core and click on yourself with it.

**Comment by BobJoga** [comment]
Probably related to the legion core nerf that citadel did. I'll fix this presto.
