### ISSUE TITLE
Timer of hidden walls can be circumvented

### ISSUE THREAD

**Issue by Avunia** [Skyrat-SS13/Skyrat13#1756]
## Round ID:
1297

## Date and Time of Issue:
2020-05-07 12:34 CEST/UTC+2 / 6:34 Server time

## What Map did this Issue occur on:
Box Station

## Reproduction:

1. Find a hidden wall
2. Start pushing it and just move away instantly
3. Walk into the wall, which looks like its closed, but actually opened

This was reproducable on the maint bar hidden door in Box Station. Could also reproduce with a hidden door in maint north-east of chapel.

Link to possibly affecting commit: 810278e

## Possible Screenshots of the Issue in question:
Direct link: https://gfycat.com/sillyimpracticalcrocodileskink
![](https://thumbs.gfycat.com/SillyImpracticalCrocodileskink-size_restricted.gif)

**Comment by Akrilla** [comment]
fml I swear I tested this... I'll fix
