### ISSUE TITLE
IPCs no longer have machine language even though it wasn't reverted.

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#1773]
See https://github.com/Skyrat-SS13/Skyrat13/pull/1177

Most likely caused by Azarak's playing. Even though it's still in the code.

[Image](https://i.imgur.com/j5imeEm.png)

**Comment by Akrilla** [comment]
They do, it's part of a current testmerge. You need to select the language as an additional one on your character settings.
