### ISSUE TITLE
Sentient PyroSlime vs Resin

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat13#1810]
Issue reported from  Round ID: 1313 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

![dreamseeker_GubHjihCEC](https://user-images.githubusercontent.com/49801705/81466108-90474a80-9194-11ea-89fa-45022f6453f4.png)

Took the pyro-anom slime ghostspawner, found myself in a pre-existing atmos resin block, totally locked down without recourse.

Let's give slimes some kind of damage against atmos resin?  Spawning in as a sentient pyro slime and being 100% stripped of the ability to play _because a quick atmostech already resin'd the anom room_ is uh... frustrating, to say the least. And not the sort of thing I want for the game - hard lockouts are shitty design.
This isn't a common issue, but the level of player shutdown is serious, and a fix should not be hard.

**Comment by jjpark-kb** [comment]
This isnt an issue. Ill label it as a suggestion.

**Comment by jjpark-kb** [comment]
actually, closing. If you are a sentient slime and stuck, pray or ahelp and ask for assistance.
