### ISSUE TITLE
Wing colour doesn't persist through gameserver restarts

### ISSUE THREAD

**Issue by Avunia** [Skyrat-SS13/Skyrat13#1833]
## Round ID:
1325, among others

## Date and Time of Issue:
2020-05-08
2020-05-09
2020-05-10 17:39 CEST / 11:39 Server time

## What Map did this Issue occur on:
Box Station, Meta Station, Delta Station
Probably any.

## Reproduction:
1. Have character with feathery wings
2. Make sure wing colour is **not** #FFFFFF / White
3. Play game until round ends (or server crashes)
4. Wait for reconnect and check wing colour again
5. Wing colour will reset to #FFFFFF

E.g. My used colour is 221,221,204, but my wings reset to white every time a new round begins, having to specifically edit and save it again before the game starts.

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/1858 Should have fixed this

**Comment by Avunia** [comment]
Issue still persist after recent update
#1941
