### ISSUE TITLE
Deluxe switchblade in-hand icons are reversed, crafting menu won't open

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat13#1863]
## Round ID:
1328

## Date and Time of Issue:
Approximately 11:30pm on May 10, 2020

## What Map did this Issue occur on:
Metastation

## Reproduction:
Created a switchblade in the crafting menu using the exact amount of materials needed, then withdrew exact amount from ore reclaimer needed to make deluxe switchblade, plus a cable coil and high capacity power cell from tool storage. After crafting the deluxe switchblade using the crafting menu, I closed the menu and the switchblade appeared to be open when in-hand, though the sprite on my character didn't show the blade and the tooltip for the item showed its force as 'very low.' Pressing the Use hotkey closed the blade in my inventory, but updated the tooltip, on-character sprite, and damage to behave as if it were open. Damage from blade when in the 'open' state appears to work fine even though the inventory icon is closed, as tested on a pair of unfortunate monkies and thankfully not the twitchy quartermaster that made me want to make a blade to begin with.

Additionally, I had to reconnect to get the crafting menu to open again after crafting this item. Clicking the crafting menu button did nothing until I reconnected.

The normal switchblade seems to be working fine.

**Comment by BobJoga** [comment]
Fixed in the last version of my PR. Server should be updated soon.

**Comment by TehSplinterCell** [comment]
Roger that. As for the crafting aspect of the bug, I think it may have been that my character was laying down when I tried to open the menu. Not sure. I made this report the day after the round in question.

**Comment by ShadeAware** [comment]
Please close solved issues, @TehSplinterCell
