### ISSUE TITLE
Delta Station disposals mass driver fires straight into the permabrig walls

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat13#1865]
## Round ID: 
N/A, any round on Delta Station

## Date and Time of Issue:
N/A

## What Map did this Issue occur on:
Delta Station

## Reproduction:
Not much more to it than the title. The mass driver fires un-recycled debris at the prison wing to the east. This could potentially be fixed by changing the launch path to go northwards and moving the solars at the northeast of the station out of the way.

**Comment by jjpark-kb** [comment]
fixing.
