### ISSUE TITLE
Polychromatic Cloak doesnt apply selected colors

### ISSUE THREAD

**Issue by EldritchSigma** [Skyrat-SS13/Skyrat13#1916]
## Date and Time of Issue: Any time, any date

2 weeks ago

## Reproduction and explanation:

Get a polychromatic cloak from loadout. Spawn in (as lizard or any other race), swap colors. Apply cloak to self. Cloak primary color and secondary color is white. Tertiary color is applied.

## Expected Behavior:

Polychromatic cloak has chooseable primary and secondary colors.

**Comment by jjpark-kb** [comment]
fixed.
