### ISSUE TITLE
Floating Icons with Storage

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat13#1986]
## Round ID:
1375

## Date and Time of Issue:
3:12PM 5/16/20202

## What Map did this Issue occur on:
MetaStation

## Reproduction:
Set **Force Slot Storage HUD** to enabled
Fill up your bag with loose items
Close your bag menu
Stare in awe and wonder at the floating icons which you can now click without ever opening your bag!

## Possible Screenshots of the Issue in question:
![image](https://user-images.githubusercontent.com/57020074/82128264-d51c4400-9787-11ea-8e48-566533fc3476.png)

**Comment by jjpark-kb** [comment]
this should be solved.
