### ISSUE TITLE
Station(s) Science Protolathe

### ISSUE THREAD

**Issue by Afya212** [Skyrat-SS13/Skyrat13#1998]
On box station the science department protolathe isn't a techfab like it is for every other department.

It should be changed from `/obj/machinery/rnd/production/protolathe/department/science` to `/obj/machinery/rnd/production/techfab/department/science`

**Comment by BobJoga** [comment]
It shouldn't be changed as that might break things, but a proper protolathe needs to be added.

**Comment by Afya212** [comment]
Oh wait i'm just big dumb and can't see.

**Comment by Afya212** [comment]
This also seems to be the case with Pubby station, I'd recommend just combing through all of them.

**Comment by jjpark-kb** [comment]
Protolathes are the lower version of techfabs. Techfabs can print circuits, which the protolathes cannot do. This is intended.
