### ISSUE TITLE
Synthetic Trait: Hunger Issues

### ISSUE THREAD

**Issue by skyvaal** [Skyrat-SS13/Skyrat13#2054]
Issue reported from  Round ID: 1399 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 512

**Information:**
Character has the trait of "Synthetic" which states they do not get hungry.
Moodlet, and HUD are indicating that my Character is getting hungry. Eating food does not rectify this issue, so really the issue is that the hunger still decays over time, and cannot be replenished.
![image](https://user-images.githubusercontent.com/20910942/82387714-acb67300-9a2f-11ea-9299-1a5f86852b34.png)
![image](https://user-images.githubusercontent.com/20910942/82387640-80025b80-9a2f-11ea-9fe4-138416df65d4.png)

Synthetic  Skill is NOT showing as selected, despite being selected on the Character Customisation.
![image](https://user-images.githubusercontent.com/20910942/82387902-23537080-9a30-11ea-9b1d-48a33866fe89.png)
![image](https://user-images.githubusercontent.com/20910942/82387771-d1124f80-9a2f-11ea-8ed8-a2886296633d.png)

**Reproduction:**
- Make Character with Synthetic Trait
- Play
- Over time, hunger decreases, effecting character as normal
- Failed Workaround: Attempting to eat food does not fill hunger back up as normal...

**Comment by BobJoga** [comment]
I think you can satisfy your gunger like IPCs do, by simply sucking out energy of an APC with the arm cable thing. I will test this and update the quirk to be more coherent.

**Comment by Strazyplus** [comment]
This is not a bug and is functioning as intended. however, synth trait should rephrase the mention of hunger to recharging. and you should have the arm recharging cable skill on top left. else you need to drink fuel, do this by getting a flask and fill it up with a fuel canister.

**Comment by Afya212** [comment]
Yarp, not a bug, but could be made a request to rephrase it/make it more obvious.
