### ISSUE TITLE
Fennec Body Marking

### ISSUE THREAD

**Issue by Ol-Vinny** [Skyrat-SS13/Skyrat13#2088]
## Round ID:
1418

## Date and Time of Issue:
05/21/20 5:00AM

## Reproduction:
1. Create a character
2. Make them an Anthromorph
3. Select "Fennec" for Species Markings
4. Notice the empty space near the forehead of the character, persists past spawning in with said character.

## Possible Screenshots of the Issue in question:
![image](https://user-images.githubusercontent.com/42969794/82573617-3a36b780-9b43-11ea-9854-d476e75bf120.png)
![image](https://user-images.githubusercontent.com/42969794/82573723-5a667680-9b43-11ea-9d42-6ca95b008ddd.png)

**Comment by jjpark-kb** [comment]
tested, and I didnt find an issue... perhaps it was already solved or there was an issue clientside.

**Comment by jjpark-kb** [comment]
Reopening, another player has had issues that are similar. However, the player had an issue with using synthetic sergals.

Perhaps its an issue with anthromorphs themselves?

**Comment by Afya212** [comment]
It seems to be an issue with the anthro sprite that also happens on cit depending on the hair style you select. 
![image](https://user-images.githubusercontent.com/54920261/83772950-f028f800-a651-11ea-967b-497a1b895eac.png)

**Comment by Poojawa** [comment]
Hello!

I'm the spriter/coder for the species things, and I thought I had fixed this upstream. 

I was attempting to make anthromorphic species have varied headshapes so they weren't all just generic human head forms


![](https://i.gyazo.com/e6c12e2e671eba70073073363f203388.png)


So stuff like Sergals would look better. I'll double check y'all's sprites real quick. Don't hesitate to ping me for any further weirdness.
