### ISSUE TITLE
Radio doesn't work when being fireman carried,

### ISSUE THREAD

**Issue by Raeschen** [Skyrat-SS13/Skyrat13#2173]
Issue reported from  Round ID: 1460 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

Be fireman carried. try to use radio. Doesn't work!

**Comment by Afya212** [comment]
I know what's causing that, not sure if it's intended or not though.

**Comment by Afya212** [comment]
After talkin with the other maintainers, this is indeed intended.
