### ISSUE TITLE
*Circle does not auto gottem

### ISSUE THREAD

**Issue by MrPangle** [Skyrat-SS13/Skyrat13#2196]
## Date and Time of Issue:

12am EST, 5/27/2020

## Testmerges (If Applicable):

Issue may be caused from merging new health system, and the combination of leg and foot targeting?

## Reproduction:

the *circle emote puts an item in your hand that when somebody examines your legs or feet, they'll get got, however. that functionally seems to be broken.

do *circle emote, get somebody else to target legs, and examine. Tried it on TG station, worked fine.

**Comment by Afya212** [comment]
We're a downstream of Cit, tested and got the bug there.
