### ISSUE TITLE
Couple of vox issues (Language, N2) 

### ISSUE THREAD

**Issue by Raeschen** [Skyrat-SS13/Skyrat13#2218]
## Reproduction:

1. Vox do not get their vox-pidgin language after the languages menu update
2. Clown vox box has o2, not n2

**Comment by Avunia** [comment]
Number 2 will be fixed by #2257 ~~also i really should refactor those checks into a single proc maybe~~

**Comment by Avunia** [comment]
Number 1 will be fixed by #2220
