### ISSUE TITLE
There are no budget cards in the departmental head lockers.

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#2383]
Round ID 1545, boxstation, I looted both the HoP locker and the CMO locker and the budget cards were noticeably absent.

Given the fact that department budgets still exist (you can see your departments budget on your ID card) I found it very jarring that they weren't in the lockers.

Let people commit monetary theft, damnit.

**Comment by jjpark-kb** [comment]
I fixed this with my ATM pr.
