### ISSUE TITLE
strange rock no sprite/invisible

### ISSUE THREAD

**Issue by Raeschen** [Skyrat-SS13/Skyrat13#2465]
Issue reported from  Round ID: 1582 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

a subtype of the strange rocks seems to be invisible. Some are visible, some not.

![mzpmDhy](https://user-images.githubusercontent.com/30182250/84398120-d5312780-abff-11ea-9132-8effba9de9c6.png)

**Comment by Owai-Seek** [comment]
Also reported here:
https://github.com/Skyrat-SS13/Skyrat13/issues/2413

**Comment by jjpark-kb** [comment]
fixed!
