### ISSUE TITLE
Delivery Chute Issue.

### ISSUE THREAD

**Issue by TheNick5527** [Skyrat-SS13/Skyrat13#2514]
## Reproduction: When in the Cargo Delivery room and you attempt to deliver an item via wrap>tag>conveyer, all crates go straight to the disposals room with the recycler. Crates did not auto-load into delivery chute. GameAdmin Relquen had to modify the map in-round to allow me to manually load them through the delivery system.
Neither I or Relquen (Bluespace Tech) could open the original windoor, had to be deleted.

## Possible Screenshots of the Issue in question:
No screenshot of before, but this is the edit:
https://gyazo.com/5c6eaf9eed373026a0531bb3c213cb18

**Comment by KathrinBailey** [comment]
Looking into this now, it looks like disposals isn't set up correctly.
