### ISSUE TITLE
Honey Balm "Blooming" and Seed Packet sprites missing.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#2572]
## Round ID:

1618

## Date and Time of Issue:

6-16-20 ~4:30 PM EST

## Reproduction:

Honey Balm is a finicky plant to mutate, and is a Cit exclusive, so not many know about it.

Mutate Poppy>Lily>Bee Balm>Honey Balm

The fully grown Honey Balm has no sprite, nor do the seed packets, but the plant on the floor does.

## Possible Screenshots of the Issue in question:
![AelcaqNgVK](https://user-images.githubusercontent.com/7543955/84825464-76005800-afef-11ea-869f-fb998a5894ca.png)
![WyJQsuC9Zp](https://user-images.githubusercontent.com/7543955/84825493-7f89c000-afef-11ea-8604-85e804a98288.png)

**Comment by jjpark-kb** [comment]
even though there was a damn mirror PR that said it fixed it, it still is fucked

**Comment by Owai-Seek** [comment]
What. I guess I'll have to test this, it worked over on cit.

**Comment by Owai-Seek** [comment]
@jjpark-kb Check between the two PRs, mirror bot missed a file.

icons/obj/hydroponics/harvest.dmi
