### ISSUE TITLE
Clarke Ore Box not functioning as intended.

### ISSUE THREAD

**Issue by davidchan13** [Skyrat-SS13/Skyrat13#2585]
## Round ID:

1621

## Date and Time of Issue: 

2020-06-17 03:30:00

## What Map did this Issue occur on: 

Box (Any)

## Reproduction:
Build a Clarke Mech
Mine Ore with Drill or Plasma Cutter
Return to ORM and dump Ore box
Ore box is removed from mech instead of simply ejecting contents.
Realize you can't reinstall orebox because Clamp is not compatible with Clarke
Cry as your mining mech is now useless for ore collection.

Long version, Clarke is meant to have a built in (non-removable) ore box that dumps ore when interacted with. When it was ported over, someone missed this check and made the box remove able, which makes the mech nearly useless for mining since it can harvest exactly one load and can't collect ore after that because the Hydraulic Clamp is incompatible with the mech so they can not be reloaded.

## Possible Screenshots of the Issue in question:
![9841748215ae9e936bff6c965df788d3](https://user-images.githubusercontent.com/12998418/84870145-868eed80-b044-11ea-8522-a9047fd23892.png)

**Comment by BobJoga** [comment]
I have a fix currently up for it. Thanks for reporting this anyway, i'll update the PR to include this as a linked issue.
