### ISSUE TITLE
Bonfire dupes objects it cooks.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#2643]
## Round ID:
1065

## Date and Time of Issue:
6-21-20 6:30 PM EST

## Reproduction:

Do the thing.

**Comment by davidchan13** [comment]
I thought this was intentional so ashwalkers could produce enough food to feed the tribe?

**Comment by Owai-Seek** [comment]
I don't know why something like this would be intentional, lizards can eat plants.

**Comment by Owai-Seek** [comment]
Will possibly be fixed by the following upstream PR.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12565

**Comment by Owai-Seek** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat13/pull/2663
