### ISSUE TITLE
Cheems don't revives from the burger

### ISSUE THREAD

**Issue by NopemanMcHalt** [Skyrat-SS13/Skyrat13#2665]
## Round ID:
1665

## Date and Time of Issue:
2020-06-23 05:10

## What Map did this Issue occur on:
Delta Station

## Testmerges (If Applicable):
#2313 #2390 #2536 #2573 #2518 #2587 (seriously doesn't seem to be related that much)

## Reproduction:

1. "I can't believe Cheems is fucking dead!"
2. Acquire burger.
3. Attempt to bap (click) Cheems with burger, or leave said burger near him.
4. @BobJoga this is serious.

## Possible Code Reference
```c#
/mob/living/simple_animal/pet/dog/cheems/Move(atom/newloc, direct)
	. = ..()
	if(.)
		for(var/obj/item/reagent_containers/food/snacks/burger/burbger in view(1, src))
			visible_message("<span class='danger'><b>\The [src]</b> consumes the [burbger]!</span>")
			qdel(burbger)
			revive(full_heal = 1)

/mob/living/simple_animal/pet/dog/cheems/attacked_by(obj/item/I, mob/living/user)
	. = ..()
	if(.)
		if(istype(I, /obj/item/reagent_containers/food/snacks/burger))
			qdel(I)
			if(stat == DEAD)
				visible_message("<b>\The [src]</b> stands right back up after nibbling the [I]!")
			else 
				visible_message("<b>\The [src]</b> swallows the [I] whole!")
			revive(full_heal = 1)
```

**Comment by BobJoga** [comment]
dont even feel like doing shit to cheems anymore because of Owai and other fun police so honestly just leaving this as is

**Comment by NopemanMcHalt** [comment]
Immersion was a mistake.
