### ISSUE TITLE
Metastation Mapping Issues / Suggestions

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#2776]
## Round ID:
1723

## What Map did this Issue occur on:
Metastation

## Reproduction:

Disposals near Arrivals will backfire.

Clown Closet is hidden in maint. You can walk into clown closet with maint access and just steal their stuff. Also, no theater nearby.

Airlock near departures is all-access.

Kitchen is missing the Eggs/Milk Fridge

## Possible Screenshots of the Issue in question:

![dreamseeker_1rJ8BvcN2o](https://user-images.githubusercontent.com/7543955/86084865-e2596d80-ba6b-11ea-94fb-5c2614ea847f.png)
(On the right, to the scaffolds)
![dreamseeker_g5KEMrahNy](https://user-images.githubusercontent.com/7543955/86084873-e71e2180-ba6b-11ea-8410-3c404f0693ff.png)

**Comment by Avunia** [comment]
Adding to the list: There's two fireclosets at arrivals right next to each other.
`X: 70, Y: 132` in file `MetaStation_Skyrat.dmm` @ a5142b70fa2c6efc5758327900a7a38be605ae87
![image](https://user-images.githubusercontent.com/6952402/86400852-93008080-bca9-11ea-890b-79c93dc23ed8.png)
