### ISSUE TITLE
Light of objects on the ground not being shown

### ISSUE THREAD

**Issue by Rayfod** [Skyrat-SS13/Skyrat13#2907]
## Testmerges (If Applicable):
'[Testmerge] Dynamic client-side processed lighting on a component' by Azarak at commit

## Reproduction:
Any light creating object that can be picked up (Lamps, glowsticks, flashlights) when dropped on the ground, only makes light if it is in your view range. Even then, that light doesn't actually increase your view range into the lit up areas. Only structures (APCs, wall lights, etc) or items actively in a character's inventory actually create proper light that allows you to see, and not just lights up the dark tiles
This works fine when it's locked in a locker
- Reported by (ThatGuyFromThatPlace) discord ID

## Possible Screenshots of the Issue in question:
![pic1](https://user-images.githubusercontent.com/63320341/87305790-576e7d80-c517-11ea-8ffd-bd16a6c91612.png)
![pic2](https://user-images.githubusercontent.com/63320341/87305809-5ccbc800-c517-11ea-8829-d16b94d06ac7.png)
![pic3](https://user-images.githubusercontent.com/63320341/87305816-5fc6b880-c517-11ea-80dc-f93e06e30983.png)
![pic4](https://user-images.githubusercontent.com/63320341/87305823-62291280-c517-11ea-9eda-6807bfd862f6.png)

**Comment by Azarak** [comment]
Should be fixed now
