### ISSUE TITLE
Language hotkeys are broken.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#2981]
## Round ID:
1867

## Date and Time of Issue:
7-18-2020

## Reproduction:
Try to use a language hotkey such as ,o ,d ,D ,t ,u ect.
It doesn't work. Same goes for many other languages. (I asked a curator to try.)
Borg chat still works it seems.

**Comment by BobJoga** [comment]
fixed now

**Comment by Owai-Seek** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/2985
