### ISSUE TITLE
EORG Menu Pref doesn't work, and has several issues.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#2982]
## Round ID:
1868

## Date and Time of Issue:
7-18-20 1:45 AM

## Info:

Plays loud over-the-top doom music.
Preference Is automatically set to yes.
Cannot set your preference to "No" in the menu.
Everyone spawns on the same tile, so you can kill everyone instantly with a bomb.

(As a note, only somewhat related to this feature, I'd really like to be able to turn the credit roll off.)

**Comment by BobJoga** [comment]
You can turn the credit roll off. There is a pref for it. Anyways, this issue is resolved by now.

**Comment by Owai-Seek** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/2980
https://github.com/Skyrat-SS13/Skyrat13/pull/2983
https://github.com/Skyrat-SS13/Skyrat13/pull/2989
