### ISSUE TITLE
Small item closets dont lock.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#3101]
Issue reported from  Round ID: 1931 (Skyrat SS13 - MRP-HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

Order something big (Wood, Carpet, ect) via goodiebag private order. The locker is not locked to that persons ID.

**Comment by YakumoChen** [comment]
they aren't supposed to I think, they contain a selection of orders?

**Comment by Owai-Seek** [comment]
They're supposed to personally locked lockers for when personal orders contain items too big for the breifcase, -probably- an upstream issue.

**Comment by Owai-Seek** [comment]
I was mistaken with this, the lockers -look- like private order lockers, but they're for small item orders, so the price is lower overall, but it isn't shipped in a crate. This makes it so their cost can be significantly lower.
