### ISSUE TITLE
VR sleepers don't work

### ISSUE THREAD

**Issue by DogZeroX** [Skyrat-SS13/Skyrat13#321]
When you click Connect to VR you get the followed message, nothing else
*Transferring to virtual world...
Virtual avatar missing, attempting to create one...
****Virtual world misconfigured, aborting transfer****"

**Comment by SpaceVampire** [comment]
This is a config level issue. Its simply not enabled on the server at the moment.

**Comment by BobJogaIsForkinBanned** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/1345
Yeah sorry.
