### ISSUE TITLE
Corndogs have no Sprite

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#371]
## Round ID:
704

## Reproduction:
Craft a corndog.

**Comment by Trilbyspaceclone** [comment]
your the worst
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11206

**Comment by Useroth** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat13/pull/388
