### ISSUE TITLE
Fancy Heels do not account for Digi legs.

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat13#3715]
## Round ID: 
past 20 or so rounds atleast.

## Date and Time of Issue: 
ongoing.

## What Map did this Issue occur on: 
clothing sprite issue, does not apply

## Reproduction: 
add Fancy Heels to a digitigrade leg'd character.

## Possible Screenshots of the Issue in question:
![issue](https://user-images.githubusercontent.com/58378414/204388737-db7c615b-4a2e-46b6-9e50-0f2b0b3eba84.png)

**Comment by Tastyfish** [comment]
Since it appears you made an issue in the correct repo as well (https://github.com/Skyrat-SS13/Skyrat-tg/issues/17808), I'm closing this one.
