### ISSUE TITLE
Detective Holsters Not Fitting Speedloaders

### ISSUE THREAD

**Issue by bonebrother** [Skyrat-SS13/Skyrat13#3722]
## Date and Time of Issue: 

8:59 AM 6/3/23

## What Map did this Issue occur on: 

MetaStation

## Testmerges (If Applicable): 

not sure

## Reproduction:

grab a detective's holster, or make one from leather and print speedloaders from a hacked autolathe and try to put them into the holster. theoretically, the intended idea should be for the loaders to fit in next to the detective's revolver, but this isn't the case

**Comment by Jolly-66** [comment]
https://github.com/Skyrat-SS13/Skyrat13/issues/3719
