### ISSUE TITLE
General Chat/Emote Issues

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#374]
## Round ID:
700-ish?

## Issue Highlights.
You can't press ESC or hit a Cancel button to back out of Emote (M) and and Say (T) (Maybe fixed by https://github.com/Skyrat-SS13/Skyrat13/pull/372)?
No typing indicator comes up on whisper.
Hitting OK when sending an empty /me brings open the /subtle options for Visible/Hearable.

You also can't have multiple /subtle, /me, PDA, /say messages up at the same time, which (for me) is a tad annoying as I like to have a /say and /me going at the same time to double post on a scene. It's also annoying because once you close one, all of the ones that you tried to use (but didnt show up) keep coming until you close them all.

## Reproduction:
Just do the things.

**Comment by hugmeorelse** [comment]
Cancel button is a thing now, so that's been fixed. I don't think there's any server that lets you hit "escape" to back out.

We'll take a look into the whisper and subtle thing, perhaps even the PDA.

**Comment by ShadeAware** [comment]
> 
> 
> Cancel button is a thing now, so that's been fixed. I don't think there's any server that lets you hit "escape" to back out.
> 
> We'll take a look into the whisper and subtle thing, perhaps even the PDA.

Actually, Citadel lets you use the ESC key to quit out of text boxes, /me boxes, and OOC/LOOC boxes @hugmeorelse . Not sure if this is still the case after the typing indicators, though.

**Comment by CinderWC** [comment]
Closing and opening this due to a consistent visual bug with Github on my mobile and hoping that fixes it

**Comment by CinderWC** [comment]
That fixed it thank god
