### ISSUE TITLE
Podpeople don't have Customisation

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#405]
## Round ID:
???

## Reproduction:
Just be a plant person. The server config sets -actual- pod-people as a roundstart race instead of pod-weak, meaning they get no customization options to play with. Podweak already has customization at the cost of much weaker "free" healing.

> /datum/species/pod/pseudo_weak
> 	name = "Anthromorphic Plant"
> 	id = "podweak"
> 	species_traits = list(EYECOLOR,HAIR,FACEHAIR,LIPS,MUTCOLORS)
> 	mutant_bodyparts = list("mam_tail", "mam_ears", "mam_body_markings", "mam_snouts", "taur", "legs")
> 	default_features = list("mcolor" = "FFF","mcolor2" = "FFF","mcolor3" = "FFF", "mam_snouts" = "Husky", "mam_tail" = "Husky", "mam_ears" = "Husky", "mam_body_markings" = "Husky", "taur" = "None", "legs" = "Normal Legs")
> 	limbs_id = "pod"
> 	light_nutrition_gain_factor = 7.5
> 	light_bruteheal = 0.2
> 	light_burnheal = 0.2
> 	light_toxheal = 0.7

**Comment by Azarak** [comment]
Was a config issue, should be fixed now
