### ISSUE TITLE
Bandanas don't show up on head slots

### ISSUE THREAD

**Issue by Nilsius** [Skyrat-SS13/Skyrat13#423]
## Round ID:

738

## Reproduction:

Try wearing any bandana on your head.

(The sprites exist for them in the code, they just don't show up ingame on the mob's heads. Bandana masks do work!)

**Comment by BobJoga** [comment]
This has been left untouched for far too long. I'll code dive and see what went wrong probably tomorrow.

**Comment by CinderWC** [comment]
This issue has been adressed and fixed since this thread was made.

@Azarak or @Useroth please close this
