### ISSUE TITLE
Chocolate jelly donut has no sprite

### ISSUE THREAD

**Issue by ForrestWick** [Skyrat-SS13/Skyrat13#536]
What the title says. Chocolate jelly donuts have no visible sprite, do they're just invisible. 
![image](https://user-images.githubusercontent.com/54997375/75942016-ee834480-5e56-11ea-82d0-2e7f35a2d8b5.png)

**Comment by SpaceVampire** [comment]
Fixed by this https://github.com/Skyrat-SS13/Skyrat13/pull/572
This issue should be closed now.
