### ISSUE TITLE
Making a table using metal makes an "iron table"; clashes with standard "table" found everywhere else

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat13#595]
Round ID: Any, but I discovered this on 828

Reproduction:
Get two sheets of metal; make one into rods; make a table frame; build a table from the other sheet; cry on the inside as you get an ugly grey table that fits nothing in the rest of the entire station.
![222121](https://user-images.githubusercontent.com/57020074/76157569-72982f00-60d8-11ea-8038-de248b8c77c7.PNG)

**Comment by Azarak** [comment]
I may be wrong but this seems like an intended thing from upstream? I hate it too

**Comment by ShadeAware** [comment]
It may be intentional? But it's still awful and shouldn't be a thing.

**Comment by BobJoga** [comment]
I think this has been fixed. Should probably be closed.

**Comment by Useroth** [comment]
Resolved by https://github.com/Skyrat-SS13/Skyrat13/pull/740
