### ISSUE TITLE
Cannot Print Vendor or Minesweeper Board

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#713]
## Round ID:
Honestly, I forgot, and I havent reported it yet. Happened 3-11

## Reproduction:
Research vendors boards, instead of printing individual or universal vendor boards, the only one you get is Booze-o-Mat.

As for Arcade boards, apparently you can research others, but not Minesweeper.

**Comment by BobJoga** [comment]
Probably upstream issue, i recommend reporting there. But i will make a modular fix if need be.

**Comment by BobJoga** [comment]
EEEEEEEEhhhh i'll just fix it here tomorrow.

**Comment by Owai-Seek** [comment]
I guess the problem is that you need restocking units, not vendor boards, but the booze-o-mat is an odd exception?

**Comment by Owai-Seek** [comment]
Seems you can screwdriver the board to change it, not sure about the minesweeper one, however.
