### ISSUE TITLE
Some odd clothing issues.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat13#717]
## Round ID:
891, Server time 2020-03-16 00:57:00

## Reproduction:
Unknown, but I've had the issue several times, and always asked others in the area if they see it as well. The answer is always a yes.

Person themselves looks to be wearing clothes. People around them see nothing, and assume they are naked.

![image](https://user-images.githubusercontent.com/7543955/76724487-799aef00-6721-11ea-97e4-b7fc6d68c59c.png)

Reconnecting seems to force an update and make the clothing visible.

I have seen the issue with:
Tactical Turtlenecks
Sundresses
Blue Schoolgirl Uniforms.

**Comment by BobJoga** [comment]
I think this is just a "byond being byond" issue tbh, don't know how we could feasibly fix it, much less in a modular way.

**Comment by Owai-Seek** [comment]
I don't remember ever having this problem upstream, but byond versions have updated since then.

**Comment by CinderWC** [comment]
As there have been no further reports about this issue and i have found no way of recreating this issue. I will be closing it.

If this happens again, please reopen this ticket or make a new one.
