### ISSUE TITLE
solar panel glass bug

### ISSUE THREAD

**Issue by Armyguy** [Skyrat-SS13/Skyrat13#796]
Issue reported from  Round ID: 934 (Skyrat SS13 - MRP to HRP [Open House, Weekly Events])

Reporting client version: 512

Adding glass to solar panels does not use the glass just drops it at your feet

**Comment by BobJoga** [comment]
Will look into it tomorrow.

**Comment by CinderWC** [comment]
Tested this. This no longer happens and appears to have been fixed upstream
