### ISSUE TITLE
Syndicate Ship  (Missing things?)

### ISSUE THREAD

**Issue by Grunnyyy** [Skyrat-SS13/Skyrat13#815]
Syndicate Ship
ID's are inbisible
And so are the NT mobs
There is no food on the ship
The Ships storages Gear Crates are all Empty only the Cargopods have
There is no way to set up the machine since you have no Beakers
Or Matter bins, except one
Recommendation for that: Add Beakers to Glassworking and give them glassworking tools
Some Cleaning things would be nice
Aswell as a fuel or water tank
As the welder has finite uses

**Comment by BobJoga** [comment]
thanks bob for your totally working fucking submissions to skyrats wow its so good bob
anyways ill fix it probably today

**Comment by BobJoga** [comment]
well that wasn't fixed. i might fix it tomorrow.

**Comment by CinderWC** [comment]
@Grunnyyy Would you be able to elaborate on this?
What Syndicate Ship exactly are you talking about as i dont seem to find the one you are talking about

**Comment by CinderWC** [comment]
I have scoured all map files that had the word "syndi" in them. None of them have the issues that are described here, leading me to believe that this issue has long been resolved considering the age of this thread.

If this issue persists, please reopen this issue with more information
