### ISSUE TITLE
CTF Desert Eagle has the wrong Magazines supplied

### ISSUE THREAD

**Issue by Grunnyyy** [Skyrat-SS13/Skyrat13#818]
As the title says, in CTF you get a side arm Desert Eagle and two magazines in your pockets. The ones you have in the pocket currently are not the ones that fit into that Desert Eagle

**Comment by BobJoga** [comment]
I'll try and send a PR to fix this upstream

**Comment by Grunnyyy** [comment]
This is actually two mags for the CTF rifle, so I just misremembered
