### ISSUE TITLE
Star-Kist not mixing properly

### ISSUE THREAD

**Issue by Jamini** [Skyrat-SS13/Skyrat13#875]
Issue reported from  Round ID: 965 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 512

Star-Kist (in cans from vendors) and mixed manually (1u OJ, 1u Cola) no longer seem to react. 

Expected Behavior:

Cola and Orange Juice mix to create star-kist when in the same container

Current Behavior: 

The reagents do not mix

![image](https://user-images.githubusercontent.com/1775680/77479271-db301d00-6df5-11ea-903f-bee477b49b09.png)

**Comment by Owai-Seek** [comment]
Star-Kist isn't a reagent, not even on TG, it's just a mix of space cola and orange juice.

> /obj/item/reagent_containers/food/drinks/soda_cans/starkist
	name = "Star-kist"
	desc = "The taste of a star in liquid form. And, a bit of tuna...?"
	icon_state = "starkist"
	list_reagents = list(/datum/reagent/consumable/space_cola = 15, /datum/reagent/consumable/orangejuice = 15)
	foodtype = SUGAR | FRUIT | JUNKFOOD

**Comment by IronEleven** [comment]
Yeah it's been 50% cola 50% OJ for years.
