### ISSUE TITLE
The PanDemic UI is crashing 

### ISSUE THREAD

**Issue by DeusSepulchre** [Skyrat-SS13/Skyrat13#943]
Issue reported from  Round ID: 983 (Skyrat SS13 - MRP to HRP [Apply on Discord, Weekly Events])

Reporting client version: 513

When attempting to expand the description of the symptom Viral Aggressive Metabolism, a new symptom that I believe was added 2 days ago and was ported from Beestation virology code, the window crashes. 
![BSOD](https://user-images.githubusercontent.com/56988374/77719699-2c314400-6fa3-11ea-9ea1-453b37d31898.PNG)

**Comment by BobJoga** [comment]
fixed by https://github.com/Skyrat-SS13/Skyrat13/pull/944
