### ISSUE TITLE
Heirophant music restarts every time you hit it

### ISSUE THREAD

**Issue by CoreFlare** [Skyrat-SS13/Skyrat13#999]
## Explanation:

All megafauna now have a special music that plays when you fight them, yes? And for most this works perfectly. Bubblegum has DOOM 2016 music, Colossus gets some sick ass shadow of the colossus, and Heirophant gets some cool undertale mad dummy remix.

Or at least, the first 2 notes, before it loops again.

## Reproduction:

Step 1: Download latest master, compile, run.
Step 2: Zip down to lavaland, hit the heirophant. Music plays fine, right?
Step 3: Hit the heirophant again. The music should restart from the beginning.

**Comment by BobJoga** [comment]
Oh good lord. I'll look into this.

**Comment by BobJoga** [comment]
i want to die
https://github.com/Skyrat-SS13/Skyrat13/pull/1005

**Comment by BobJoga** [comment]
its fixed please close thanks

**Comment by CoreFlare** [comment]
uh fuck i guess closed???? this should've autoclosed on merge lmao
